name: Build and test

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying
  schedule:
    - cron: '0 0 * * 6'

jobs:
  test:
    name: Multi-OS Cargo test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest,macOS-latest]
        rust: [nightly]
        include:
          - os: macOS-latest
            rust: 'nightly'
            components: 'rustfmt, clippy, rust-src'
            targets: 'x86_64-apple-darwin'
          - os: ubuntu-latest
            rust: 'nightly'
            components: 'rustfmt, clippy'
            targets: 'x86_64-unknown-linux-musl'
    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
         rust-version: ${{ matrix.rust }}
         components: ${{ matrix.components || '' }}
         targets: ${{ matrix.targets || '' }}
    - uses: actions/checkout@v2.3.4
    - name: Check Cargo availability
      run: cargo --version
    - name: Test
      run: |
        # Don't run integration tests here, as they require KVM
         cargo test --lib -- --nocapture
         cargo test --doc -- --nocapture


  build-docker:
    runs-on: [self-hosted]
    steps:
        - uses: actions/checkout@v1
        - name: Print user
          run: echo ${{ secrets.DOCKERUSER }}
        - name: Login to DockerHub Registry
          run:  docker login -u ${{ secrets.DOCKERUSER }} -p ${{ secrets.DOCKERTOKEN }}
          #run: echo ${{ secrets.DOCKERTOKEN }} | docker login -u ${{ secrets.DOCKERUSER }} --password-stdin
        - name: Get the version
          id: vars
          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        - name: Build the tagged Docker image
          run: docker build . --file Dockerfile --tag jounathaen/uhyve:latest
        - name: Push the tagged Docker image
          run: docker push jounathaen/uhyve:latest

  kvm-full-test-suite:
    name: Rusty-Hermit Unit & KVM integration Tests
    runs-on: [self-hosted]
    needs: build-docker
    container:
      image: jounathaen/uhyve:latest
      options: '--device /dev/kvm'

    steps:
    - name: List devices
      run: ls /dev/
    - uses: hecrj/setup-rust-action@v1
      with:
         rust-version: nightly
         components: 'rustfmt, clippy'
         targets: 'x86_64-unknown-linux-gnu'
    - uses: actions/checkout@v2.3.4
    - name: Check Cargo availability
      run: cargo --version
    - name: Integration Tests
      run: cargo test
    - name: Generate integration test coverage
      run: |
        ./generate_test_coverage.sh --print-coverage
    - name: Generate unit test coverage
      run: |
        bash <(curl -s https://codecov.io/bash) -f
    - uses: codecov/codecov-action@v1.5.0
      with:
        files: ./coveralls.json


  fmt-check:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 'nightly'
          components: 'rustfmt'
          targets: 'x86_64-unknown-linux-gnu'
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Check Formatting
        run: cargo fmt -- --check
      - name: Check Integration Test Formatting
        working-directory: ./tests/test-kernels
        run: cargo fmt -- --check
